name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "0.14.3"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Build source
        run: npm run -s build

      - name: Check formatting
        run: purs-tidy check src test

      - name: Run tests
        run: npm run -s test

      - name: Build examples
        run: npm run -s example-all

      - name: Check examples formatting
        run: purs-tidy check examples
